import React from "react";
import { Sequence, Audio, staticFile } from "remotion";
import { PhraseTimeline } from "../components/sync/PhraseTimeline";
import { TextSlamScene, CTAEndCardScene } from "../components/scenes";
import { V1_PHRASE_CONFIGS } from "../timing/v1-phrases";

// Timing data is loaded from JSON files generated by the audio pipeline.
// During development (before audio is generated), we use placeholder timings.
// Once audio is generated, timing JSONs are saved to public/audio/*.
//
// For now, we import the phrase configs and will wire up actual timing
// data once the audio pipeline runs. The composition uses estimated
// durations based on the original scene timing.

// Placeholder timing: approximate the original scene durations
// Scene 1: ~29.7s, Scene 2: ~22.4s, Scene 3: ~15.6s, Scene 4: ~13.3s
// Total VO: ~81s + 3s intro silence = ~84s = 2520 frames

/**
 * Video 1 -- "The Problem"
 *
 * Structure:
 *  - 0:00-0:03  Text slam intro (3s silence leader)
 *  - 0:03-end   PhraseTimeline drives all visuals synced to VO
 *  - Final ~13s  CTA end card overlaid
 *  - Single <Audio> plays the full mixed voiceover track
 *
 * Once timing JSONs are generated, the PhraseTimeline reads word-level
 * timestamps and renders the correct visual component at each phrase.
 */
export const Video1TheProblem: React.FC = () => {
  // Estimated frame positions (will be replaced by actual timing data)
  const INTRO_SILENCE_FRAMES = 90; // 3s
  const SCENE1_FRAMES = 891; // 29.7s
  const SCENE2_FRAMES = 673; // 22.4s
  const SCENE3_FRAMES = 469; // 15.6s
  const SCENE4_FRAMES = 399; // 13.3s
  const VO_START = INTRO_SILENCE_FRAMES;
  const VO_TOTAL = SCENE1_FRAMES + SCENE2_FRAMES + SCENE3_FRAMES + SCENE4_FRAMES;
  const CTA_START = VO_START + SCENE1_FRAMES + SCENE2_FRAMES + SCENE3_FRAMES;

  // Build placeholder phrase timings distributed across the VO duration.
  // These will be replaced with real timing data from ElevenLabs.
  const placeholderTimings = buildPlaceholderTimings(
    V1_PHRASE_CONFIGS.map((c) => c.phrase),
    VO_TOTAL,
    VO_START
  );

  return (
    <>
      {/* 0:00-0:03  Text slam (over 3s silence leader) */}
      <Sequence from={0} durationInFrames={INTRO_SILENCE_FRAMES}>
        <TextSlamScene text="Your team is drowning." glitchColor="#06B6D4" />
      </Sequence>

      {/* 0:03-end  Phrase-synced visuals for all VO */}
      <Sequence from={VO_START} durationInFrames={VO_TOTAL}>
        <PhraseTimeline
          phraseTimings={placeholderTimings}
          phraseConfigs={V1_PHRASE_CONFIGS}
          backgroundGlow={{ brand: true, cyan: false }}
        />
      </Sequence>

      {/* CTA end card overlay during scene 4 */}
      <Sequence from={CTA_START} durationInFrames={SCENE4_FRAMES}>
        <CTAEndCardScene />
      </Sequence>

      {/* Full voiceover audio track */}
      <Audio src={staticFile("audio/v1-mixed.wav")} />
    </>
  );
};

/**
 * Build evenly-distributed placeholder timings for development.
 * Each phrase gets an equal slice of the total duration.
 */
function buildPlaceholderTimings(
  phrases: string[],
  totalFrames: number,
  frameOffset: number
) {
  const perPhrase = Math.floor(totalFrames / phrases.length);
  return phrases.map((phrase, i) => ({
    phrase,
    startSeconds: (frameOffset + i * perPhrase) / 30,
    endSeconds: (frameOffset + (i + 1) * perPhrase) / 30,
    startFrame: i * perPhrase,
    endFrame: (i + 1) * perPhrase,
    durationFrames: perPhrase,
    wordTimings: [],
  }));
}
