import React from "react";
import { AbsoluteFill, Sequence, Audio, staticFile } from "remotion";
import { DarkBackground } from "../components/backgrounds/DarkBackground";
import { SentenceVisual } from "../components/sync/SentenceVisual";

import type { VideoTimingData } from "../types";

// Timing data is loaded from the JSON generated by the audio pipeline.
// During development (before audio is generated), we use fallback estimated timings.
let timingData: VideoTimingData;
try {
  timingData = require("../../public/audio/v1-timing.json");
} catch {
  // Fallback: evenly-distributed placeholder timings for development
  timingData = {
    videoId: "video1",
    fps: 30,
    totalDurationFrames: 1050,
    sentences: [
      { key: "v1-s1", visual: "TextSlam", startFrame: 0, durationFrames: 90, audioFile: null, displayText: "Your team is drowning." },
      { key: "v1-s2", visual: "SpreadsheetCopyPaste", startFrame: 90, durationFrames: 120, audioFile: "v1-s2.mp3" },
      { key: "v1-s3", visual: "TicketRouting", startFrame: 210, durationFrames: 110, audioFile: "v1-s3.mp3" },
      { key: "v1-s4", visual: "EveryCompany", startFrame: 320, durationFrames: 90, audioFile: "v1-s4.mp3" },
      { key: "v1-s5", visual: "SadChatbot", startFrame: 410, durationFrames: 90, audioFile: "v1-s5.mp3" },
      { key: "v1-s6", visual: "ThatsAdorable", startFrame: 500, durationFrames: 60, audioFile: "v1-s6.mp3" },
      { key: "v1-s7", visual: "LogoRevealSync", startFrame: 560, durationFrames: 100, audioFile: "v1-s7.mp3" },
      { key: "v1-s8", visual: "PillarCards", startFrame: 660, durationFrames: 120, audioFile: "v1-s8.mp3" },
      { key: "v1-s9", visual: "PercentCounter", startFrame: 780, durationFrames: 110, audioFile: "v1-s9.mp3" },
      { key: "v1-s10", visual: "CTAEndCard", startFrame: 890, durationFrames: 160, audioFile: "v1-s10.mp3" },
    ],
  };
}

/**
 * Video 1 -- "The Problem"
 *
 * Per-sentence architecture: each sentence is its own Remotion Sequence
 * synced to its own audio segment. No PhraseTimeline, no phrase matching.
 */
export const Video1TheProblem: React.FC = () => {
  return (
    <AbsoluteFill>
      <DarkBackground showBrandGlow showCyanGlow />

      {/* Full voiceover audio track */}
      <Audio src={staticFile("audio/v1-mixed.wav")} />

      {/* Per-sentence visual sequences */}
      {timingData.sentences.map((sentence) => (
        <Sequence
          key={sentence.key}
          from={sentence.startFrame}
          durationInFrames={sentence.durationFrames}
        >
          <SentenceVisual
            visualName={sentence.visual}
            durationFrames={sentence.durationFrames}
            displayText={sentence.displayText}
          />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
